version: 1
services:
  - type: web
    name: Food Tracker - Calorie Scanner
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    publish: dist
    routes:
      - src: /.*
        dest: /index.html
