version: 1
services:
  - type: web
    name: Food Tracker - Calorie Scanner
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    publish: build
    routes:
      - src: /.*        # Match all routes
        dest: /index.html  # Serve index.html for all routes
